### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by SystemUpdate** [StatsCraft-MC/StatsCraft#2]
Hello,

What are we going to use for CI? From what I can see, the pom has jenkins but then the repo has both Travis CI and Circle CI. I say we use one and stick with one.

**Comment by sgdc3** [comment]
we can keep multiple ci services

**Comment by sgdc3** [comment]
i'll setup our own jenkins until we get the server

**Comment by sgdc3** [comment]
but it's good practice to have alternative servi

**Comment by sgdc3** [comment]
sorry closed because i was from mobile xD

**Comment by SirFaizdat** [comment]
I have _never_ seen a project that has used more than one CI server. Let's stick with one.

**Comment by sgdc3** [comment]
at least 2, jenkins + circle

**Comment by SirFaizdat** [comment]
What's the point of two?

**Comment by sgdc3** [comment]
because if our jenkins goes offline we need an alternative

**Comment by sgdc3** [comment]
trust me, i work on authme and we always had more ci services

**Comment by sgdc3** [comment]
Why are we talking about CI if the project is still at begin? In my opinion we should keep both circle.yml and .travis.yml files. Jenkins will be our main CI service, travis is slow but it has a good uptime, circle is faster but sometimes it goes off

**Comment by SirFaizdat** [comment]
Because we have no direction right now. We don't even have a central place to chat yet.

**Comment by sgdc3** [comment]
Anyway our integration services:
CI:
- Jenkins: main, fastest, customizable, built-in maven repository
- Travis: slow, good uptime
- Circle: fast, normal uptime
Coverage:
- coveralls
Chat:
- Gitter
Dependency updates:
- Versioneye
